/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { PaginatedBudgetCategoryResponseList } from '../models';
/**
 * BudgetCategoriesApi - axios parameter creator
 * @export
 */
export const BudgetCategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list of all budget categories
         * @param {number} [page] A page number within the paginated result set.
         * @param {string} [search] A search term.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBudgetsBudgetCategoriesList: async (page?: number, search?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/budgets/budget_categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookieAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("sessionid")
                    : await configuration.apiKey;
                localVarQueryParameter["sessionid"] = localVarApiKeyValue;
            }

            // authentication tokenAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BudgetCategoriesApi - functional programming interface
 * @export
 */
export const BudgetCategoriesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get a list of all budget categories
         * @param {number} [page] A page number within the paginated result set.
         * @param {string} [search] A search term.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBudgetsBudgetCategoriesList(page?: number, search?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedBudgetCategoryResponseList>>> {
            const localVarAxiosArgs = await BudgetCategoriesApiAxiosParamCreator(configuration).apiBudgetsBudgetCategoriesList(page, search, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BudgetCategoriesApi - factory interface
 * @export
 */
export const BudgetCategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get a list of all budget categories
         * @param {number} [page] A page number within the paginated result set.
         * @param {string} [search] A search term.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBudgetsBudgetCategoriesList(page?: number, search?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedBudgetCategoryResponseList>> {
            return BudgetCategoriesApiFp(configuration).apiBudgetsBudgetCategoriesList(page, search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BudgetCategoriesApi - object-oriented interface
 * @export
 * @class BudgetCategoriesApi
 * @extends {BaseAPI}
 */
export class BudgetCategoriesApi extends BaseAPI {
    /**
     * Get a list of all budget categories
     * @param {number} [page] A page number within the paginated result set.
     * @param {string} [search] A search term.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BudgetCategoriesApi
     */
    public async apiBudgetsBudgetCategoriesList(page?: number, search?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedBudgetCategoryResponseList>> {
        return BudgetCategoriesApiFp(this.configuration).apiBudgetsBudgetCategoriesList(page, search, options).then((request) => request(this.axios, this.basePath));
    }
}
