/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BudgetCategoryRelationCreationRequest
 */
export interface BudgetCategoryRelationCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof BudgetCategoryRelationCreationRequest
     */
    budget: number;
    /**
     * 
     * @type {number}
     * @memberof BudgetCategoryRelationCreationRequest
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof BudgetCategoryRelationCreationRequest
     */
    amount: string;
    /**
     * 
     * @type {boolean}
     * @memberof BudgetCategoryRelationCreationRequest
     */
    is_percentage: boolean;
}
