/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BudgetCategoryRelationBulkUpdateRequest } from './budget-category-relation-bulk-update-request';
/**
 * 
 * @export
 * @interface BudgetCategoryRelationsBulkUpdateRequest
 */
export interface BudgetCategoryRelationsBulkUpdateRequest {
    /**
     * 
     * @type {Array<BudgetCategoryRelationBulkUpdateRequest>}
     * @memberof BudgetCategoryRelationsBulkUpdateRequest
     */
    category_relations: Array<BudgetCategoryRelationBulkUpdateRequest>;
}
