/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BudgetCategoryResponse
 */
export interface BudgetCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof BudgetCategoryResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetCategoryResponse
     */
    typical_percentage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetCategoryResponse
     */
    typical_monthly_amount?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BudgetCategoryResponse
     */
    id: number;
}
