/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExpensesByCategory
 */
export interface ExpensesByCategory {
    /**
     * 
     * @type {number}
     * @memberof ExpensesByCategory
     */
    total_amount: number;
    /**
     * 
     * @type {number}
     * @memberof ExpensesByCategory
     */
    id: number;
}
