/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExpensesByCategory } from './expenses-by-category';
/**
 * 
 * @export
 * @interface PaginatedExpensesByCategoryList
 */
export interface PaginatedExpensesByCategoryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedExpensesByCategoryList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedExpensesByCategoryList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedExpensesByCategoryList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ExpensesByCategory>}
     * @memberof PaginatedExpensesByCategoryList
     */
    results?: Array<ExpensesByCategory>;
}
