/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PatchedExpenseCreationRequest
 */
export interface PatchedExpenseCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedExpenseCreationRequest
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedExpenseCreationRequest
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedExpenseCreationRequest
     */
    user?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedExpenseCreationRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedExpenseCreationRequest
     */
    category?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedExpenseCreationRequest
     */
    amount?: string;
}
