/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PatchedBudgetCategoryRelationCreationRequest
 */
export interface PatchedBudgetCategoryRelationCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedBudgetCategoryRelationCreationRequest
     */
    budget?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedBudgetCategoryRelationCreationRequest
     */
    category?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedBudgetCategoryRelationCreationRequest
     */
    amount?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedBudgetCategoryRelationCreationRequest
     */
    is_percentage?: boolean;
}
