/* tslint:disable */
/* eslint-disable */
/**
 * Financial Aide Backend
 * API Backend for Financial Aide open-source budgeting system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RegisterRequestRequest
 */
export interface RegisterRequestRequest {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof RegisterRequestRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestRequest
     */
    password: string;
}
